### ISSUE TITLE
Filename too long

### ISSUE THREAD

**Issue by eeshvardasikcm** [alexvanyo/composelife#774]
Tried to clone the repository. Some png filenaming is too long for my windows pc. I am installing to an already nested file system. I don't want to change my file system for this interesting app. I have had similar issues in the past. Most repos are cloning okay for me. This filename you have is particularly long.

The file ends with ...[NEXUS_5_NOTNIGHT,fontScale=1.5].png
Theres three others like that one. Is it possible to reduce the file naming?

**Comment by alexvanyo** [comment]
Argh, Windows file name restrictions...

Those files are automatically named via [Paparazzi](https://github.com/cashapp/paparazzi) when generating and validating snapshots, so there doesn't look to be a super easy way to change them.

If you ignore those files, the rest of the app should run fine, the only thing that wouldn't work is the tests verifying those screenshots. I don't personally develop on Windows, so hopefully the rest does work!

**Comment by eeshvardasikcm** [comment]
> Those files are automatically named via [Paparazzi](https://github.com/cashapp/paparazzi) when generating and validating snapshots, so there doesn't look to be a super easy way to change them.
> 
> If you ignore those files, the rest of the app should run fine, the only thing that wouldn't work is the tests verifying those screenshots. I don't personally develop on Windows, so hopefully the rest does work!

Great answer. I will try forking again and see if I can integrate the app without those files. Maybe remove paparazzi entirely.
